name: CI/CD for Spring Boot

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to Environment
#        run: |
#          # Add your deployment script or commands here
