name: Java CI

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DBURL: jdbc:postgresql://postgres:5432/BingemonTest
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      APIKEY: ${{ secrets.APIKEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Print Environment Variables
        run: |
          echo "DBURL=${DBURL}"
          echo "DBUSER=${DBUSER}"
          echo "DBPASS=${DBPASS}"
          echo "APIKEY=${APIKEY}"

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Package JAR
        run: mvn package
